-- Create a table named SALES_DATA
CREATE TABLE SALES_DATA (
    S_NO NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    SALESPERSON_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER,
    SALES_AMOUNT NUMBER,
    TAX_AMOUNT NUMBER,
    TOTAL_AMOUNT NUMBER
);


INSERT INTO SALES_DATA (S_NO, ORDER_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID, QUANTITY, UNIT_PRICE, SALES_AMOUNT, TAX_AMOUNT, TOTAL_AMOUNT)
VALUES (1, 1295, 101, 1001, 201, 5, 10.00, 50.00, 5.00, 55.00);

INSERT INTO SALES_DATA (S_NO, ORDER_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID, QUANTITY, UNIT_PRICE, SALES_AMOUNT, TAX_AMOUNT, TOTAL_AMOUNT)
VALUES (2, 1296, 102, 1002, 202, 3, 15.00, 45.00, 4.50, 49.50);
/* 1) Write a program to fetch data from table SALES for a given orderid and display the data.
(Use %TYPE when declaring variables)*/
DECLARE 
s_no SALES_DATA.S_NO%TYPE ;
s_id SALES_DATA.ORDER_ID%TYPE := 1295 ;
s_pid SALES_DATA.PRODUCT_ID%TYPE ;
s_cid SALES_DATA.CUSTOMER_ID%TYPE;
s_sid SALES_DATA.SALESPERSON_ID%TYPE ;
s_quantity SALES_DATA.QUANTITY%TYPE;
s_unitprice SALES_DATA.UNIT_PRICE%TYPE ;
s_salesamount SALES_DATA.SALES_AMOUNT%TYPE ;
s_tax SALES_DATA.TAX_AMOUNT%TYPE ;
s_total SALES_DATA.TOTAL_AMOUNT%TYPE ;
BEGIN
SELECT S_NO, ORDER_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID, QUANTITY, UNIT_PRICE, SALES_AMOUNT, TAX_AMOUNT, TOTAL_AMOUNT
INTO s_no, s_id, s_pid, s_cid, s_sid, s_quantity, s_unitprice, s_salesamount, s_tax, s_total
 
;FROM SALES_DATA
WHERE ORDER_ID = s_id; -- Assuming ORDER_ID uniquely identifies a row


DBMS_OUTPUT.PUT_LINE(s_no);
DBMS_OUTPUT.PUT_LINE(s_id);
DBMS_OUTPUT.PUT_LINE(s_pid);
DBMS_OUTPUT.PUT_LINE(s_cid);
DBMS_OUTPUT.PUT_LINE(s_sid);
DBMS_OUTPUT.PUT_LINE(s_quantity);
DBMS_OUTPUT.PUT_LINE(s_unitprice);
DBMS_OUTPUT.PUT_LINE(s_salesamount);
DBMS_OUTPUT.PUT_LINE(s_tax);
DBMS_OUTPUT.PUT_LINE(s_total);


END ;
SELECT * FROM SALES_DATA;


/*2) Write a program to insert data into SALES table.*/
DECLARE 
s_no SALES_DATA.S_NO%TYPE :=3 ;
s_id SALES_DATA.ORDER_ID%TYPE := 1297 ;
s_pid SALES_DATA.PRODUCT_ID%TYPE :=103;
s_cid SALES_DATA.CUSTOMER_ID%TYPE :=1003;
s_sid SALES_DATA.SALESPERSON_ID%TYPE :=203;
s_quantity SALES_DATA.QUANTITY%TYPE :=10;
s_unitprice SALES_DATA.UNIT_PRICE%TYPE :=20;
s_salesamount SALES_DATA.SALES_AMOUNT%TYPE := 55;
s_tax SALES_DATA.TAX_AMOUNT%TYPE :=5;
s_total SALES_DATA.TOTAL_AMOUNT%TYPE:=60 ;

BEGIN 
INSERT INTO SALES_DATA(S_NO, ORDER_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID, QUANTITY, UNIT_PRICE, SALES_AMOUNT, TAX_AMOUNT, TOTAL_AMOUNT)
VALUES (s_no, s_id, s_pid, s_cid, s_sid, s_quantity, s_unitprice, s_salesamount, s_tax, s_total) ;
COMMIT ;
END ;
SELECT * FROM SALES_DATA;


/*3) Write a program to update data in SALES table for a given orderid (Change order
amount to 100).
*/
DECLARE
s_id SALES_DATA.ORDER_ID%TYPE := 1297 ;
BEGIN 
UPDATE SALES_DATA SET ORDER_ID = 100 where ORDER_ID = s_id ;
END;

/*4) Write a program to delete data from SALES table for a given orderid.*/
DECLARE
s_id SALES_DATA.ORDER_ID%TYPE := 100 ;
BEGIN
DELETE FROM SALES_DATA WHERE ORDER_ID= s_id;
end;
